### ISSUE TITLE
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView

### ISSUE THREAD

**Issue by allthesignals** [ksin/ember-bingo#7]
Hi! I'd like to repurpose this for a charity bingo game. When I run it, I see this:

> The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

I'm not sure where this is coming from but here's the log:

> =================================================================================
> 
> ENV Summary:
> 
>   TIME: Wed Sep 09 2020 22:56:14 GMT-0400 (Eastern Daylight Time)
>   TITLE: ember
>   ARGV:
>   - /Users/wmattgardner/.nvm/versions/node/v14.4.0/bin/node
>   - /Users/wmattgardner/ember-bingo/node_modules/.bin/ember
>   - serve
>   EXEC_PATH: /Users/wmattgardner/.nvm/versions/node/v14.4.0/bin/node
>   TMPDIR: /var/folders/gs/x79h3r4179gbvdh2pry1lcfc0000gn/T
>   SHELL: /bin/zsh
>   PATH:
>   - /var/folders/gs/x79h3r4179gbvdh2pry1lcfc0000gn/T/yarn--1599706571597-0.17796011883975482
>   - /Users/wmattgardner/ember-bingo/node_modules/.bin
>   - /Users/wmattgardner/.config/yarn/link/node_modules/.bin
>   - /Users/wmattgardner/.nvm/versions/node/v14.4.0/libexec/lib/node_modules/npm/bin/node-gyp-bin
>   - /Users/wmattgardner/.nvm/versions/node/v14.4.0/lib/node_modules/npm/bin/node-gyp-bin
>   - /Users/wmattgardner/.nvm/versions/node/v14.4.0/bin/node_modules/npm/bin/node-gyp-bin
>   - /Users/wmattgardner/.rvm/gems/ruby-2.6.4/bin
>   - /Users/wmattgardner/.rvm/gems/ruby-2.6.4@global/bin
>   - /Users/wmattgardner/.rvm/rubies/ruby-2.6.4/bin
>   - /Users/wmattgardner/.nvm/versions/node/v14.4.0/bin
>   - /Users/wmattgardner/.yarn/bin
>   - /Users/wmattgardner/.config/yarn/global/node_modules/.bin
>   - /usr/local/bin
>   - /usr/bin
>   - /bin
>   - /usr/sbin
>   - /sbin
>   - /Users/wmattgardner/.rvm/bin
>   PLATFORM: darwin x64
>   FREEMEM: 99057664
>   TOTALMEM: 17179869184
>   UPTIME: 131299
>   LOADAVG: 6.0341796875,4.02490234375,3.109375
>   CPUS:
>   - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
>   - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
>   - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
>   - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
>   - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
>   - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
>   - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
>   - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
>   - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
>   - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
>   - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
>   - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 2600
>   ENDIANNESS: LE
>   VERSIONS:
>   - ares: 1.16.0
>   - brotli: 1.0.7
>   - cldr: 37.0
>   - icu: 67.1
>   - llhttp: 2.0.4
>   - modules: 83
>   - napi: 6
>   - nghttp2: 1.41.0
>   - node: 14.4.0
>   - openssl: 1.1.1g
>   - tz: 2019c
>   - unicode: 13.0
>   - uv: 1.37.0
>   - v8: 8.1.307.31-node.33
>   - zlib: 1.2.11
> 
> ERROR Summary:
> 
>   - broccoliBuilderErrorStack: [undefined]
>   - code: ERR_INVALID_ARG_TYPE
>   - codeFrame: [undefined]
>   - errorMessage: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
>   - errorType: [undefined]
>   - location:
>     - column: [undefined]
>     - file: [undefined]
>     - line: [undefined]
>   - message: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
>   - name: TypeError
>   - nodeAnnotation: [undefined]
>   - nodeName: [undefined]
>   - originalErrorMessage: [undefined]
>   - stack: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
>     at Object.writeFileSync (fs.js:1380:5)
>     at module.exports (/Users/wmattgardner/ember-bingo/node_modules/ember-cli/lib/utilities/attempt-never-index.js:26:6)
>     at Builder.build (/Users/wmattgardner/ember-bingo/node_modules/ember-cli/lib/models/builder.js:156:5)
>     at Watcher_build [as build] (/Users/wmattgardner/ember-bingo/node_modules/ember-cli-broccoli-sane-watcher/index.js:116:6)
>     at new Watcher (/Users/wmattgardner/ember-bingo/node_modules/ember-cli-broccoli-sane-watcher/index.js:24:24)
>     at Watcher.constructWatcher (/Users/wmattgardner/ember-bingo/node_modules/ember-cli/lib/models/watcher.js:26:12)
>     at new Watcher (/Users/wmattgardner/ember-bingo/node_modules/ember-cli/lib/models/watcher.js:19:41)
>     at ServeTask.run (/Users/wmattgardner/ember-bingo/node_modules/ember-cli/lib/tasks/serve.js:31:39)
>     at /Users/wmattgardner/ember-bingo/node_modules/ember-cli/lib/models/command.js:243:46
>     at tryCatcher (/Users/wmattgardner/ember-bingo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:326:21)
> 
> =================================================================================
>

**Comment by allthesignals** [comment]
Addressed by https://github.com/ksin/ember-bingo/pull/8
